#!/usr/bin/env python
from pathlib import Path

from notion_to_md.cli import parse_args
from notion_to_md.folder import Folder


def main(dirpath: Path) -> None:
    folder = Folder()
    folder.process(dirpath)


if __name__ == '__main__':
    args = parse_args()
    dirpath = args.path

    main(Path(dirpath))
