#!/usr/bin/env python
from pathlib import Path

from notion_to_md.cli import parse_args
from notion_to_md.file import File


def main(dirpath: Path) -> None:
    for path in dirpath.iterdir():
        if path.suffix == '.md':
            File.process_md(path)
        elif path.suffix in ('.jpg', '.png'):
            File.process_img(path)
        elif path.is_dir():
            main(path)


if __name__ == '__main__':
    args = parse_args()
    dirpath = args.path

    main(Path(dirpath))
