#!/usr/bin/env python
from notion_to_md.cli import parse_args
from notion_to_md.data import FileInfo
from notion_to_md.file import File
from notion_to_md.work_with_dir.get_ import get_dir_by_path

if __name__ == '__main__':
    args = parse_args()
    filepath = args.path

    dirpath = get_dir_by_path(filepath)
    lines = tuple(File.read(filepath))
    fileinfo = FileInfo(dirpath, filepath, '', lines)
    heading = File.get_heading(fileinfo)

    if heading:
        fileinfo.heading = heading

        File.copy(fileinfo)
